###
GET http://localhost:3000/signin
Content-Type:  application/json

{
    "email":"admin@admin.com",
    "password":"admin123"
}

###
POST  http://localhost:3000/signup
Content-Type: application/json

{
    "name":"admin",
    "password":"admin123",
    "phone":4231243223,
    "email":"admin@admin.com"
}